## Bereite Datensatz vor

In [ ]:
import pandas as pd

face_master = pd.read_csv('../data/2024-06-14-posts-all_faces_labeled.csv')

In [ ]:
face_master.head()

,id,filename,label
0,b248b1d2-1780-4b4c-8529-571b0246a9e5,olafscholz/2021-09-13_07-45-59_UTC.jpg,Olaf Scholz
1,d83b5202-1f81-4b16-b8c8-360f0e6051e5,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,NaN
2,95c9174b-5389-4ccb-89ac-98de4be55d9e,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,Olaf Scholz
3,2d573a4a-21f5-464f-aef4-8700597752c1,olafscholz/2021-09-17_10-42-46_UTC_2.jpg,NaN
4,3539ae42-9adf-4733-a703-024b662d8eff,olafscholz/2021-09-17_10-42-46_UTC_2.jpg,NaN

In [ ]:
face_master['account_name'] = face_master['filename'].apply(lambda x: x.split('/')[0])

In [ ]:
face_master.rename(columns={'label': 'name'}, inplace=True)

In [ ]:
face_master.head()

,id,filename,name,account_name
0,b248b1d2-1780-4b4c-8529-571b0246a9e5,olafscholz/2021-09-13_07-45-59_UTC.jpg,Olaf Scholz,olafscholz
1,d83b5202-1f81-4b16-b8c8-360f0e6051e5,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,NaN,olafscholz
2,95c9174b-5389-4ccb-89ac-98de4be55d9e,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,Olaf Scholz,olafscholz
3,2d573a4a-21f5-464f-aef4-8700597752c1,olafscholz/2021-09-17_10-42-46_UTC_2.jpg,NaN,olafscholz
4,3539ae42-9adf-4733-a703-024b662d8eff,olafscholz/2021-09-17_10-42-46_UTC_2.jpg,NaN,olafscholz

In [ ]:
# Ich arbeite jetzt nur mit den Kanzlerkandidaten Accounts damit als erstes diesen Filter
selected_accounts = ['armin_laschet', 'abaerbock', 'christlichsozialeunion',
       'christianlindner', 'cdu', 'fdp', 'die_gruenen', 'markus.soeder',
       'spdde', 'olafscholz']

face_master = face_master[face_master['account_name'].isin(selected_accounts)]

In [ ]:
len(face_master['filename'].unique())

735

In [ ]:
accounts_dict = {
  "armin_laschet": ["Armin Laschet"],
  "spdde": ["Olaf Scholz"],
  "christianlindner": ["Christian Lindner"],
  "abaerbock": ["Annalena Baerbock"],
  "cdu": ["Armin Laschet"],
  "olafscholz": ["Olaf Scholz"],
  "die_gruenen": ["Annalena Baerbock"],
  "christlichsozialeunion": ["Markus Söder"],
  "fdp": ["Christian Lindner"],
  "markus.soeder":  ["Markus Söder"],
}

In [ ]:
# Function to check if the model is in the list for the account_name
def check_model(row, col, accounts_dict):
    # Get the list of valid models for the account_name
    valid_models = accounts_dict.get(row['account_name'], [])

    # Return 'Unknown' if the model is not in the list, else return the model
    return row[col] if row[col] in valid_models else 'Unknown'


# Apply the function to each row of the DataFrame
df_filtered = face_master.copy()
df_filtered['name'] = df_filtered.apply(lambda row: check_model(row, "name", accounts_dict), axis=1)

df_filtered = df_filtered[df_filtered['name'] != 'Unknown']

In [ ]:
df_filtered.head()

,id,filename,name,account_name
0,b248b1d2-1780-4b4c-8529-571b0246a9e5,olafscholz/2021-09-13_07-45-59_UTC.jpg,Olaf Scholz,olafscholz
2,95c9174b-5389-4ccb-89ac-98de4be55d9e,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,Olaf Scholz,olafscholz
6,4c441268-34c9-4ee1-a7f2-82c5277a354e,olafscholz/2021-09-20_11-29-19_UTC.jpg,Olaf Scholz,olafscholz
11,47d76ade-4763-44e7-a3b8-7341f6915efc,olafscholz/2021-09-16_19-01-33_UTC_2.jpg,Olaf Scholz,olafscholz
13,955c61d6-2354-43e5-a3c9-acd5b9ec6003,olafscholz/2021-09-21_20-52-10_UTC.jpg,Olaf Scholz,olafscholz

In [ ]:
df_filtered = df_filtered.groupby('filename')['name'].agg(lambda x: ', '.join(x)).reset_index()

----

**Warum sind in zwei Datensätzen unterschiedlich viele Zahlen an Bildern?**

-> *Ich habe den falschen Datensatz verwendet!!*

In [ ]:
df_test = pd.read_csv('../data/2024-07-01-Faces-in-Posts-filtered.csv')

In [ ]:
df_test.head()

,Unnamed: 0,face_uuid,filename,Ground Truth,match_file,match_score,model,distance_metric,number_of_hits,Model,account_name
0,0,b248b1d2-1780-4b4c-8529-571b0246a9e5,olafscholz/2021-09-13_07-45-59_UTC.jpg,Olaf Scholz,addb18d2-ca87-4104-b149-5ecb974f1432.png,0.520983,Facenet512,euclidean_l2,40.0,Olaf Scholz,olafscholz
1,2,95c9174b-5389-4ccb-89ac-98de4be55d9e,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,Olaf Scholz,fb89d12e-d3a5-48c2-b506-eca8454e847b.png,0.547668,Facenet512,euclidean_l2,40.0,Olaf Scholz,olafscholz
2,6,4c441268-34c9-4ee1-a7f2-82c5277a354e,olafscholz/2021-09-20_11-29-19_UTC.jpg,Olaf Scholz,c27ee252-e37c-4074-92b5-20e300431107.png,0.479990,Facenet512,euclidean_l2,40.0,Olaf Scholz,olafscholz
3,11,47d76ade-4763-44e7-a3b8-7341f6915efc,olafscholz/2021-09-16_19-01-33_UTC_2.jpg,Olaf Scholz,c27ee252-e37c-4074-92b5-20e300431107.png,0.625600,Facenet512,euclidean_l2,38.0,Olaf Scholz,olafscholz
4,13,955c61d6-2354-43e5-a3c9-acd5b9ec6003,olafscholz/2021-09-21_20-52-10_UTC.jpg,Olaf Scholz,f124d4ca-3c2d-40fd-a3a4-81e0a32b39d5.png,0.648758,Facenet512,euclidean_l2,38.0,Olaf Scholz,olafscholz

In [ ]:
# prompt: I want to find rows in df_test that are not in df_filtered based on the column filename

rows_not_in_filtered = df_test[~df_test['filename'].isin(df_filtered['filename'])]

# Print the number of rows not in filtered
print(f"Number of rows not in filtered: {len(rows_not_in_filtered)}")

Number of rows not in filtered: 254

In [ ]:
rows_not_in_filtered

,Unnamed: 0,face_uuid,filename,Ground Truth,match_file,match_score,model,distance_metric,number_of_hits,Model,account_name
68,877,b48a69cb-dcea-4e35-9d93-185518ea5ccf,cdu/2021-09-24_19-39-33_UTC_9.jpg,Armin Laschet,NaN,NaN,NaN,NaN,NaN,Unknown,cdu
87,1028,30daa5a5-990d-4c36-acfb-f6e0bec1c3f9,armin_laschet/2021-09-17_12-59-07_UTC_4.jpg,Armin Laschet,NaN,NaN,NaN,NaN,NaN,Unknown,armin_laschet
126,1227,618ea7ec-e794-4a14-8a01-0ec9fafe104e,armin_laschet/2021-09-22_14-55-06_UTC_5.jpg,Armin Laschet,NaN,NaN,NaN,NaN,NaN,Unknown,armin_laschet
150,1486,3891e58a-d740-45d0-bed8-a0b6cb02b3d0,christianlindner/2021-09-17_19-33-56_UTC_1.jpg,Christian Lindner,aba5bb44-8485-4f0d-9b60-c596194fa33b.png,0.674915,Facenet512,euclidean_l2,20.0,Christian Lindner,christianlindner
151,1487,dd4cf437-959a-475f-a710-d39ea1a3ccea,christianlindner/2021-09-26_10-50-55_UTC_7.jpg,Christian Lindner,cebfea5f-bce7-498c-9d1a-5b80c9e97361.png,0.586596,Facenet512,euclidean_l2,20.0,Christian Lindner,christianlindner
...,...,...,...,...,...,...,...,...,...,...,...
396,4308,e808b1ba-0ac9-4ee9-8607-9fde70847a17,markus.soeder/2021-09-24_10-51-37_UTC_2.jpg,Markus Söder,49bdb61e-e0b0-4666-9cf0-5c7ab16b2516.png,0.782939,Facenet512,euclidean_l2,18.0,Markus Söder,markus.soeder
397,4312,ca65b901-94a8-4aff-94f6-6dce55c35126,markus.soeder/2021-09-15_14-55-59_UTC_2.jpg,Markus Söder,NaN,NaN,NaN,NaN,NaN,Unknown,markus.soeder
398,4318,4a4856a4-aff1-4793-ba0b-e660dab4dbb9,markus.soeder/2021-09-16_10-22-44_UTC_3.jpg,Markus Söder,49bdb61e-e0b0-4666-9cf0-5c7ab16b2516.png,0.920581,Facenet512,euclidean_l2,6.0,Markus Söder,markus.soeder
399,4320,89118434-38d3-4375-83f7-984eb0e4b376,markus.soeder/2021-09-19_12-43-37_UTC.jpg,Markus Söder,49bdb61e-e0b0-4666-9cf0-5c7ab16b2516.png,0.809743,Facenet512,euclidean_l2,26.0,Markus Söder,markus.soeder
454,4819,d8ad75d3-fbf0-4ad4-91b6-39f01edffcac,cdu/2021-09-21_09-28-34_UTC.jpg,Armin Laschet,NaN,NaN,NaN,NaN,NaN,Unknown,cdu

## Lade Bilder

In [ ]:
!unzip ../data/posts.zip

## GPT Annotation

In [ ]:
!pip install openai backoff

Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (1.35.7)
Collecting backoff
  Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (2.7.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2024.6.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (2.18.4)
Installing collected packages: backoff
Successfully installed backoff-2.2.1

In [ ]:
prompt = """
Imagine you were a social science researcher, conducting an analysis of the 2021 German Federal election campaign. The image shows the front-runner(s): {NAME}. We're interested in measuring individualization of candidates in the election campaign.  How many people are in the focus of the image? Just the candidate, a small group of politicians, or a large group? Count the number of clearly visible individuals.
Select the right choice: 'GPT Count': ["0", "1", "2", "3+"]
Additionally: Is there a crowd of spectators visible? 'GPT Crowd': ["True", "False"]

Respond in valid JSON only.
"""

# Additionally: Is there a crowd of spectators visible? 'GPT Crowd': ["True", "False"]

In [ ]:
import pandas as pd
import json
import re
from pandas import json_normalize

def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if type(x) is dict:
            for a in x:
                flatten(x[a], name + a + '_')
        elif type(x) is list:
            i = 0
            for a in x:
                flatten(a, name + str(i) + '_')
                i += 1
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

def parse_response(response, identifier):
    try:
        if isinstance(response, str):
            response = json.loads(response)
        response = flatten_json(response)
        response['Image'] = identifier
        return response
    except json.JSONDecodeError:
        match = re.search(r'```json\n([\s\S]+)\n```', response)
        if match:
            try:
                json_data = json.loads(match.group(1))
                json_data = flatten_json(json_data)
                json_data['Image'] = identifier
                return json_data
            except json.JSONDecodeError:
                pass
        return {'Image': identifier, 'error': response}

In [ ]:
face_count_df = pd.read_csv('../data/2024-07-01-Person-Count-GPT-w-Crowd.csv', index_col=0)

In [ ]:
face_count_df.head()

  GPT Count  GPT Crowd                                        Image
0         1      False    armin_laschet/2021-09-12_20-45-47_UTC.jpg
1        3+       True  armin_laschet/2021-09-13_17-02-10_UTC_2.jpg
2         1      False  armin_laschet/2021-09-15_09-28-48_UTC_3.jpg
3         1      False    armin_laschet/2021-09-15_12-38-48_UTC.jpg
4         1      False    armin_laschet/2021-09-16_15-01-25_UTC.jpg

In [ ]:
import base64
import requests
from tqdm.notebook import tqdm
import time
import openai
from openai import OpenAI
import os

api_key = os.environ.get("OPENAI_API_KEY")


# OpenAI API Key
client = OpenAI(
    api_key=api_key
)

prompt_cost = 5 / 1000000
completion_cost = 15 / 1000000

total_cost = 0.0

# Function to encode the image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

import backoff
@backoff.on_exception(backoff.expo, (openai.RateLimitError, openai.APIError))
def run_request(prompt, base64_image):
  messages = [{
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": prompt
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_image}",
                        }
                    }
                ]
            }]


  return client.chat.completions.create(
                    model="gpt-4o",
                    response_format={ "type": "json_object" },
                    temperature=0,
                    messages=messages,
                    max_tokens=600)

responses = []
data = []

for index, row in tqdm(df_filtered.iterrows(), total=len(df_filtered)):
    image = row['filename']

    if image in face_count_df['Image'].values:
        print(f"Skipping {image} because it has already been processed")
        continue

    # Path to your image
    image_path = f"/content/{image}"

    # Getting the base64 string
    base64_image = encode_image(image_path)

    tmp_prompt = prompt.replace('{NAME}', row['name'])
    response = run_request(tmp_prompt, base64_image)

    # Extract the response content
    r = response.choices[0].message.content

    # Adding prompt cost
    current_prompt_cost = response.usage.prompt_tokens * prompt_cost
    current_completion_cost = response.usage.completion_tokens * completion_cost

    current_cost = current_prompt_cost + current_completion_cost
    total_cost += current_cost


    responses.append({
        'Image': image,
        'GPT Count': r
    })

    processed_data = parse_response(r, image)
    data.append(processed_data)

print(f"Total cost ${total_cost}")

In [ ]:
face_count_df_new = pd.DataFrame(data)
face_count_df = pd.concat([face_count_df, face_count_df_new])
face_count_df.to_csv('../data/2024-07-01-Person-Count-GPT-w-Crowd.csv', index = False)

In [ ]:
face_count_df

    GPT Count GPT Crowd                                        Image
0           1     False    armin_laschet/2021-09-12_20-45-47_UTC.jpg
1          3+      True  armin_laschet/2021-09-13_17-02-10_UTC_2.jpg
2           1     False  armin_laschet/2021-09-15_09-28-48_UTC_3.jpg
3           1     False    armin_laschet/2021-09-15_12-38-48_UTC.jpg
4           1     False    armin_laschet/2021-09-16_15-01-25_UTC.jpg
..        ...       ...                                          ...
246         1     False       olafscholz/2021-09-21_13-38-38_UTC.jpg
247        3+      True       olafscholz/2021-09-22_12-20-14_UTC.jpg
248         2     False     olafscholz/2021-09-22_20-57-22_UTC_2.jpg
249         2     False     olafscholz/2021-09-24_11-51-14_UTC_1.jpg
250        3+     False       olafscholz/2021-09-25_11-22-24_UTC.jpg

[479 rows x 3 columns]

In [ ]:
face_count_df.to_csv('../data/2024-07-01-Person-Count-GPT-wo-Crowd.csv')

In [ ]:
face_count_df.to_csv('../data/2024-07-01-Person-Count-GPT-w-Crowd.csv')

## Auswertung

In [ ]:
face_count_df = pd.read_csv('../data/2024-07-01-Person-Count-GPT-wo-Crowd.csv')

In [ ]:
face_count_df.rename(columns={'GPT Count': 'Count w/o Crowd'}, inplace=True)

In [ ]:
face_count_w_crowd_df = pd.read_csv('../data/2024-07-01-Person-Count-GPT-w-Crowd.csv')

In [ ]:
face_count_w_crowd_df.rename(columns={'GPT Count': 'Count w/ Crowd'}, inplace=True)

In [ ]:
face_count_df = pd.merge(face_count_df, face_count_w_crowd_df, on='Image')

In [ ]:
face_count_df

,Count w/o Crowd,Image,Count w/ Crowd,GPT Crowd
0,1,armin_laschet/2021-09-12_20-45-47_UTC.jpg,1,False
1,3+,armin_laschet/2021-09-13_17-02-10_UTC_2.jpg,3+,True
2,1,armin_laschet/2021-09-15_09-28-48_UTC_3.jpg,1,False
3,1,armin_laschet/2021-09-15_12-38-48_UTC.jpg,1,False
4,1,armin_laschet/2021-09-16_15-01-25_UTC.jpg,1,False
...,...,...,...,...
474,1,olafscholz/2021-09-21_13-38-38_UTC.jpg,1,False
475,3+,olafscholz/2021-09-22_12-20-14_UTC.jpg,3+,True
476,2,olafscholz/2021-09-22_20-57-22_UTC_2.jpg,2,False
477,2,olafscholz/2021-09-24_11-51-14_UTC_1.jpg,2,False
478,3+,olafscholz/2021-09-25_11-22-24_UTC.jpg,3+,False

In [ ]:
face_count_df.to_csv('../data/2024-07-01-Person-GPT.csv')

In [ ]:
face_count_df[face_count_df['Count w/ Crowd'] != face_count_df['Count w/o Crowd']]

,Count w/o Crowd,Image,Count w/ Crowd,GPT Crowd
8,3+,armin_laschet/2021-09-18_19-12-07_UTC_1.jpg,1,True
19,3+,armin_laschet/2021-09-21_11-03-21_UTC_3.jpg,2,False
57,3+,cdu/2021-09-16_17-02-39_UTC_5.jpg,1,True
85,3+,cdu/2021-09-19_13-42-10_UTC.jpg,1,True
101,3+,cdu/2021-09-21_18-48-32_UTC_2.jpg,2,True
163,3+,olafscholz/2021-09-14_10-23-23_UTC_3.jpg,3,False
179,3+,olafscholz/2021-09-20_18-06-50_UTC_4.jpg,1,True
196,3+,spdde/2021-09-13_16-00-15_UTC.jpg,2,False
205,0,spdde/2021-09-18_09-00-38_UTC.jpg,1,False
209,3+,spdde/2021-09-18_14-42-04_UTC_7.jpg,2,False
236,3+,abaerbock/2021-09-15_13-20-23_UTC_2.jpg,1,True
242,3+,abaerbock/2021-09-17_19-48-04_UTC_4.jpg,1,True
247,3+,abaerbock/2021-09-20_13-46-23_UTC_2.jpg,3,False
248,3+,abaerbock/2021-09-20_13-46-23_UTC_3.jpg,2,False
272,3+,abaerbock/2021-09-25_15-05-02_UTC_5.jpg,1,True
287,3+,armin_laschet/2021-09-18_19-12-07_UTC_4.jpg,5,False
291,3+,armin_laschet/2021-09-21_05-10-21_UTC_3.jpg,1,False
307,3+,cdu/2021-09-21_09-28-34_UTC.jpg,0,False
313,3+,christianlindner/2021-09-15_18-37-22_UTC_1.jpg,1,True
317,3+,christianlindner/2021-09-15_18-37-22_UTC_6.jpg,1,True
318,3+,christianlindner/2021-09-16_07-47-54_UTC.jpg,1,True
321,3+,christianlindner/2021-09-16_18-15-11_UTC_1.jpg,3,False
331,3+,christianlindner/2021-09-17_19-33-56_UTC_6.jpg,1,True
336,3+,christianlindner/2021-09-19_18-12-56_UTC_1.jpg,1,True
337,3+,christianlindner/2021-09-20_07-51-26_UTC.jpg,1,True
341,3+,christianlindner/2021-09-21_14-50-34_UTC_3.jpg,2,True
343,3+,christianlindner/2021-09-21_19-30-47_UTC_4.jpg,1,True
344,3+,christianlindner/2021-09-21_19-30-47_UTC_5.jpg,1,True
346,3+,christianlindner/2021-09-22_20-20-19_UTC_1.jpg,1,True
354,3+,christianlindner/2021-09-26_10-50-55_UTC_3.jpg,1,True
356,3+,christianlindner/2021-09-26_10-50-55_UTC_5.jpg,1,True
362,1,christlichsozialeunion/2021-09-15_19-36-35_UTC...,2,False
414,3+,markus.soeder/2021-09-15_14-55-59_UTC_1.jpg,3,False
415,3+,markus.soeder/2021-09-15_14-55-59_UTC_2.jpg,3,False
443,3+,markus.soeder/2021-09-20_14-35-36_UTC.jpg,2,False
468,3+,olafscholz/2021-09-15_11-18-08_UTC.jpg,1,False

## Experiment: Face Recognition mit GPT-4o

In [ ]:
import pandas as pd

df = pd.read_csv('../data/2024-07-03-Faces-in-Posts-unfiltered.csv')

In [ ]:
df.head()

,Unnamed: 0,face_uuid,filename,Ground Truth,match_file,match_score,model,distance_metric,number_of_hits,Model,account_name
0,0,b248b1d2-1780-4b4c-8529-571b0246a9e5,olafscholz/2021-09-13_07-45-59_UTC.jpg,Olaf Scholz,addb18d2-ca87-4104-b149-5ecb974f1432.png,0.520983,Facenet512,euclidean_l2,40.0,Olaf Scholz,olafscholz
1,1,d83b5202-1f81-4b16-b8c8-360f0e6051e5,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,Unknown,NaN,NaN,NaN,NaN,NaN,Unknown,olafscholz
2,2,95c9174b-5389-4ccb-89ac-98de4be55d9e,olafscholz/2021-09-14_10-23-23_UTC_1.jpg,Olaf Scholz,fb89d12e-d3a5-48c2-b506-eca8454e847b.png,0.547668,Facenet512,euclidean_l2,40.0,Olaf Scholz,olafscholz
3,3,2d573a4a-21f5-464f-aef4-8700597752c1,olafscholz/2021-09-17_10-42-46_UTC_2.jpg,Unknown,NaN,NaN,NaN,NaN,NaN,Unknown,olafscholz
4,4,3539ae42-9adf-4733-a703-024b662d8eff,olafscholz/2021-09-17_10-42-46_UTC_2.jpg,Unknown,NaN,NaN,NaN,NaN,NaN,Unknown,olafscholz

In [ ]:
df = df.groupby('filename').agg({
    'Ground Truth': lambda x: ', '.join(set(x)),
    'Model': lambda x: ', '.join(set(x)),
    'account_name': 'first'
    }).reset_index()

In [ ]:
df.head()

,filename,Ground Truth,Model,account_name
0,abaerbock/2021-09-13_14-02-02_UTC.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock
1,abaerbock/2021-09-13_19-36-55_UTC_1.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock
2,abaerbock/2021-09-13_19-36-55_UTC_2.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock
3,abaerbock/2021-09-13_19-36-55_UTC_3.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock
4,abaerbock/2021-09-13_19-36-55_UTC_4.jpg,"Unknown, Annalena Baerbock","Unknown, Annalena Baerbock",abaerbock

In [ ]:
!pip install openai backoff

Collecting openai
  Downloading openai-1.35.9-py3-none-any.whl (328 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.3/328.3 kB 5.8 MB/s eta 0:00:00
Collecting backoff
  Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Collecting httpx<1,>=0.23.0 (from openai)
  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (2.7.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2024.6.2)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai)
  Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 4.7 MB/s eta 0:00:00
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.7 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (2.18.4)
Installing collected packages: h11, backoff, httpcore, httpx, openai
Successfully installed backoff-2.2.1 h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 openai-1.35.9

In [ ]:
accounts_dict = {
  "armin_laschet": ["Armin Laschet"],
  "spdde": ["Olaf Scholz"],
  "christianlindner": ["Christian Lindner"],
  "abaerbock": ["Annalena Baerbock"],
  "cdu": ["Armin Laschet"],
  "olafscholz": ["Olaf Scholz"],
  "die_gruenen": ["Annalena Baerbock"],
  "christlichsozialeunion": ["Markus Söder"],
  "fdp": ["Christian Lindner"],
  "markus.soeder":  ["Markus Söder"],
}

party_dict = {
  "armin_laschet": "CDU",
  "spdde": "SPD",
  "christianlindner": "FDP",
  "abaerbock": "Die Grünen",
  "cdu": "CDU",
  "olafscholz": "SPD",
  "die_gruenen": "Die Grünen",
  "christlichsozialeunion": "CSU",
  "fdp": "FDP",
  "markus.soeder":  "CSU",
}

In [ ]:
prompt = """
Imagine you were a computational social science PhD candidate. Your goal is to measure concentrated visibility of political leaders in the 2021 Federal German election campaign on social media. Take a look at the image, does it picture {NAME}, the front-runner of the {PARTY} party? We are **not** interested in identifying individuals, we merely want to focus on the presence of absence of the {PARTY}'s front-runner!

Return a JSON dictionary:
  {
    "pictures_candidate": ["True", "False"],
    "comment": ""
  }
"""

In [ ]:
prompt = """
Imagine you are a computational social science PhD candidate. Your objective is to measure the concentrated visibility of political leaders in the 2021 Federal German election campaign on social media. Look at the image and determine if it depicts {NAME}, the front-runner of the {PARTY} party. Note: We are **not** interested in identifying individuals beyond this scope; our focus is solely on the presence or absence of the {PARTY}'s front-runner.

First, provide a comment explaining whether the image clearly depicts the {PARTY} front-runner, does not depict the front-runner, or if you are unsure. Based on this, set the `pictures_candidate` value as follows:
- "True" if the image clearly depicts the {PARTY} front-runner
- "False" if the image does not depict the {PARTY} front-runner
- "Unsure" if you cannot clearly determine if it is the {PARTY} front-runner

Please return a JSON dictionary formatted as follows:
  {
    "comment": "",
    "pictures_candidate": ["True", "False", "Unsure"]
  }
"""

In [ ]:
import pandas as pd
import json
import re
from pandas import json_normalize

def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if type(x) is dict:
            for a in x:
                flatten(x[a], name + a + '_')
        elif type(x) is list:
            i = 0
            for a in x:
                flatten(a, name + str(i) + '_')
                i += 1
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

def parse_response(response, identifier):
    try:
        if isinstance(response, str):
            response = json.loads(response)
        response = flatten_json(response)
        response['Image'] = identifier
        return response
    except json.JSONDecodeError:
        match = re.search(r'```json\n([\s\S]+)\n```', response)
        if match:
            try:
                json_data = json.loads(match.group(1))
                json_data = flatten_json(json_data)
                json_data['Image'] = identifier
                return json_data
            except json.JSONDecodeError:
                pass
        return {'Image': identifier, 'error': response}

In [ ]:
import base64
import requests
from tqdm.notebook import tqdm
import time
import openai
from openai import OpenAI
import os

api_key = os.environ.get("OPENAI_API_KEY")


# OpenAI API Key
client = OpenAI(
    api_key=api_key
)

prompt_cost = 5 / 1000000
completion_cost = 15 / 1000000

total_cost = 0.0

# Function to encode the image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

import backoff
@backoff.on_exception(backoff.expo, (openai.RateLimitError, openai.APIError))
def run_request(prompt, base64_image):
  messages = [{
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": prompt
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_image}",
                        }
                    }
                ]
            }]


  return client.chat.completions.create(
                    model="gpt-4o",
                    response_format={ "type": "json_object" },
                    temperature=0,
                    messages=messages,
                    max_tokens=600)

responses = []
data = []

for index, row in tqdm(df.sample(100).iterrows(), total=len(df)):
    image = row['filename']

    # Path to your image
    image_path = f"/content/{image}"

    # Getting the base64 string
    base64_image = encode_image(image_path)

    print(accounts_dict[row['account_name']][0])
    tmp_prompt = prompt.replace('{NAME}', accounts_dict[row['account_name']][0])
    tmp_prompt = tmp_prompt.replace('{PARTY}', party_dict[row['account_name']])
    response = run_request(tmp_prompt, base64_image)

    # Extract the response content
    r = response.choices[0].message.content

    # Adding prompt cost
    current_prompt_cost = response.usage.prompt_tokens * prompt_cost
    current_completion_cost = response.usage.completion_tokens * completion_cost

    current_cost = current_prompt_cost + current_completion_cost
    total_cost += current_cost

    processed_data = json.loads(r)
    data.append(processed_data)


    responses.append({
        **row,
        'GPT': processed_data['pictures_candidate'],
        'GPT Comment': processed_data['comment']
    })

    processed_data = parse_response(r, image)
    data.append(processed_data)

print(f"Total cost ${total_cost}")

  0%|          | 0/735 [00:00<?, ?it/s]

Annalena Baerbock
Olaf Scholz
Markus Söder
Armin Laschet
Markus Söder
Markus Söder
Armin Laschet
Armin Laschet
Annalena Baerbock
Armin Laschet
Armin Laschet
Annalena Baerbock
Armin Laschet
Christian Lindner
Markus Söder
Armin Laschet
Olaf Scholz
Annalena Baerbock
Markus Söder
Armin Laschet
Markus Söder
Armin Laschet
Armin Laschet
Annalena Baerbock
Markus Söder
Christian Lindner
Armin Laschet
Olaf Scholz
Olaf Scholz
Armin Laschet
Olaf Scholz
Christian Lindner
Markus Söder
Markus Söder
Armin Laschet
Olaf Scholz
Christian Lindner
Annalena Baerbock
Olaf Scholz
Annalena Baerbock
Markus Söder
Christian Lindner
Olaf Scholz
Armin Laschet
Markus Söder
Olaf Scholz
Annalena Baerbock
Armin Laschet
Markus Söder
Armin Laschet
Armin Laschet
Annalena Baerbock
Markus Söder
Armin Laschet
Christian Lindner
Olaf Scholz
Olaf Scholz
Markus Söder
Markus Söder
Markus Söder
Olaf Scholz
Armin Laschet
Olaf Scholz
Olaf Scholz
Markus Söder
Christian Lindner
Christian Lindner
Markus Söder
Annalena Baerbock
Armin Laschet
Christian Lindner
Annalena Baerbock
Markus Söder
Markus Söder
Armin Laschet
Annalena Baerbock
Markus Söder
Armin Laschet

INFO:backoff:Backing off run_request(...) for 0.7s (openai.BadRequestError: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'sanitizer_server_error'}})

Annalena Baerbock
Olaf Scholz
Christian Lindner
Olaf Scholz

INFO:backoff:Backing off run_request(...) for 0.0s (openai.BadRequestError: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'sanitizer_server_error'}})

Markus Söder
Markus Söder
Christian Lindner
Markus Söder
Armin Laschet
Annalena Baerbock
Annalena Baerbock
Markus Söder
Annalena Baerbock
Markus Söder
Markus Söder
Armin Laschet
Armin Laschet
Olaf Scholz
Annalena Baerbock
Olaf Scholz
Armin Laschet
Markus Söder
Total cost $0.6337000000000004

In [ ]:
new_df = pd.DataFrame(responses)
new_df.to_csv('../data/2024-07-03-Faces-in-Posts-GPT.csv')

In [ ]:
new_df = pd.read_csv('../data/2024-07-03-Faces-in-Posts-GPT.csv')
# new_df = pd.read_csv('../data/2024-07-03-Faces-in-Posts-GPT-100-sample.csv')

In [ ]:
new_df.head()

,Unnamed: 0,filename,Ground Truth,Model,account_name,GPT,GPT Comment
0,0,abaerbock/2021-09-13_14-02-02_UTC.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,['True'],NaN
1,1,abaerbock/2021-09-13_19-36-55_UTC_1.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,['False'],The image does not provide enough information ...
2,2,abaerbock/2021-09-13_19-36-55_UTC_2.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,['True'],NaN
3,3,abaerbock/2021-09-13_19-36-55_UTC_3.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,['True'],NaN
4,4,abaerbock/2021-09-13_19-36-55_UTC_4.jpg,"Unknown, Annalena Baerbock","Unknown, Annalena Baerbock",abaerbock,['True'],The image shows a person speaking at an event ...

In [ ]:
new_df['GPT'] = new_df['GPT'].apply(lambda x: x.replace("['", ""))
new_df['GPT'] = new_df['GPT'].apply(lambda x: x.replace("']", ""))

In [ ]:
new_df['GPT'] = new_df['GPT'].apply(lambda x: False if x == "Unsure" or x == "False" else True)

In [ ]:
new_df.head()

,Unnamed: 0,filename,Ground Truth,Model,account_name,GPT,GPT Comment
0,0,abaerbock/2021-09-13_14-02-02_UTC.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,True,NaN
1,1,abaerbock/2021-09-13_19-36-55_UTC_1.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,False,The image does not provide enough information ...
2,2,abaerbock/2021-09-13_19-36-55_UTC_2.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,True,NaN
3,3,abaerbock/2021-09-13_19-36-55_UTC_3.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,True,NaN
4,4,abaerbock/2021-09-13_19-36-55_UTC_4.jpg,"Unknown, Annalena Baerbock","Unknown, Annalena Baerbock",abaerbock,True,The image shows a person speaking at an event ...

In [ ]:
def check(row):
  if accounts_dict[row['account_name']][0] in row['Ground Truth']:
    return True
  else:
    return False

new_df['GT Bool'] = new_df.apply(check, axis=1)

In [ ]:
new_df.head()

,Unnamed: 0,filename,Ground Truth,Model,account_name,GPT,GPT Comment,GT Bool
0,0,abaerbock/2021-09-13_14-02-02_UTC.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,True,NaN,True
1,1,abaerbock/2021-09-13_19-36-55_UTC_1.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,False,The image does not provide enough information ...,True
2,2,abaerbock/2021-09-13_19-36-55_UTC_2.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,True,NaN,True
3,3,abaerbock/2021-09-13_19-36-55_UTC_3.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,True,NaN,True
4,4,abaerbock/2021-09-13_19-36-55_UTC_4.jpg,"Unknown, Annalena Baerbock","Unknown, Annalena Baerbock",abaerbock,True,The image shows a person speaking at an event ...,True

In [ ]:
def extract_candidate(row):
  names = row['Ground Truth'].split(', ')
  for name in names:
    if name != "Unknown":
      return name
  return "Unknown"

new_df['Candidate'] = new_df.apply(extract_candidate, axis=1)

In [ ]:
def extract_candidate_gpt(row):
  if row['GPT'] == True:
    return accounts_dict[row['account_name']][0]
  else:
    return "Unknown"

new_df['Candidate GPT'] = new_df.apply(extract_candidate_gpt, axis=1)

In [ ]:
def extract_candidate_gpt(row):
  names = row['Model'].split(', ')
  for name in names:
    if name != "Unknown":
      return name
  return "Unknown"

new_df['Candidate Model'] = new_df.apply(extract_candidate_gpt, axis=1)

In [ ]:
new_df[new_df['GPT'] != new_df['GT Bool']]

,Unnamed: 0,filename,Ground Truth,Model,account_name,GPT,GPT Comment,GT Bool,Candidate,Candidate GPT,Candidate Model
1,1,abaerbock/2021-09-13_19-36-55_UTC_1.jpg,"Unknown, Annalena Baerbock",Unknown,abaerbock,False,The image does not provide enough information ...,True,Annalena Baerbock,Unknown,Unknown
5,5,abaerbock/2021-09-14_10-00-20_UTC_1.jpg,Unknown,"Unknown, Annalena Baerbock",abaerbock,True,The image shows a person speaking at a public ...,False,Unknown,Annalena Baerbock,Annalena Baerbock
9,9,abaerbock/2021-09-14_10-00-20_UTC_6.jpg,Unknown,Unknown,abaerbock,True,The image on the bus includes a prominent figu...,False,Unknown,Annalena Baerbock,Unknown
10,10,abaerbock/2021-09-14_15-44-32_UTC.jpg,Unknown,Annalena Baerbock,abaerbock,True,NaN,False,Unknown,Annalena Baerbock,Annalena Baerbock
18,18,abaerbock/2021-09-17_11-48-57_UTC.jpg,Annalena Baerbock,Annalena Baerbock,abaerbock,False,I cannot identify individuals in images.,True,Annalena Baerbock,Unknown,Annalena Baerbock
...,...,...,...,...,...,...,...,...,...,...,...
684,684,spdde/2021-09-16_16-07-38_UTC.jpg,Unknown,Unknown,spdde,True,The image includes a newspaper article with th...,False,Unknown,Olaf Scholz,Unknown
689,689,spdde/2021-09-18_12-09-36_UTC.jpg,Olaf Scholz,Olaf Scholz,spdde,False,I cannot identify individuals in images.,True,Olaf Scholz,Unknown,Olaf Scholz
690,690,spdde/2021-09-18_14-42-04_UTC_1.jpg,Unknown,Unknown,spdde,True,The image shows a person who appears to be add...,False,Unknown,Olaf Scholz,Unknown
695,695,spdde/2021-09-18_14-42-04_UTC_6.jpg,Unknown,Olaf Scholz,spdde,True,The image features a person standing in front ...,False,Unknown,Olaf Scholz,Olaf Scholz
730,730,spdde/2021-09-24_20-19-17_UTC_3.jpg,Unknown,Unknown,spdde,True,The image contains signs with the name 'Scholz...,False,Unknown,Olaf Scholz,Unknown

In [ ]:
# prompt: let's generate a classification report including macro F1. We compare GPT and GT Bool columns. GT Bool is the ground truth column.

from sklearn.metrics import classification_report

# Generate the classification report
report = classification_report(new_df['GT Bool'], new_df['GPT'], output_dict=True)

# Print the macro F1 score
print(f"Macro F1 score: {report['macro avg']['f1-score']}")

Macro F1 score: 0.9019714826131238

In [ ]:
print(classification_report(new_df['Candidate'], new_df['Candidate GPT']))

                   precision    recall  f1-score   support

Annalena Baerbock       0.89      0.81      0.85        63
    Armin Laschet       0.97      0.98      0.98       180
Christian Lindner       0.92      0.87      0.89        62
     Markus Söder       0.97      0.92      0.95        93
      Olaf Scholz       0.89      0.91      0.90        81
          Unknown       0.86      0.89      0.87       256

         accuracy                           0.91       735
        macro avg       0.92      0.90      0.91       735
     weighted avg       0.91      0.91      0.91       735

**ACHTUNG!** Hier fehlt noch das Filtern nach Face Score!!!

In [ ]:
print(classification_report(new_df['Candidate'], new_df['Candidate Model']))

                   precision    recall  f1-score   support

Annalena Baerbock       0.92      0.78      0.84        63
    Armin Laschet       0.97      0.85      0.91       180
Christian Lindner       0.94      0.76      0.84        62
     Markus Söder       0.93      0.94      0.93        93
      Olaf Scholz       0.93      0.93      0.93        81
          Unknown       0.77      0.90      0.83       256

         accuracy                           0.87       735
        macro avg       0.91      0.86      0.88       735
     weighted avg       0.88      0.87      0.87       735

**Vorsicht bei diesen Tabellen!!!**

In [ ]:
print(classification_report(new_df['Candidate Model'], new_df['Candidate GPT']))

                   precision    recall  f1-score   support

Annalena Baerbock       1.00      0.17      0.29         6
    Armin Laschet       0.67      0.29      0.40        14
Christian Lindner       1.00      0.33      0.50         6
     Markus Söder       1.00      0.57      0.73        14
      Olaf Scholz       0.90      0.75      0.82        12
          Unknown       0.62      0.94      0.74        48

         accuracy                           0.69       100
        macro avg       0.86      0.51      0.58       100
     weighted avg       0.76      0.69      0.66       100

In [ ]:
# prompt: take a look at the previous cell. I'd like to split the data into groups based on the 'Candidate' column and generate a classification report where each name in the 'Candidate' column is one label.

# Create a dictionary to store the classification reports for each candidate
candidate_reports = {}

# Iterate through each candidate in the 'Candidate' column
for candidate in new_df['Candidate'].unique():
  # Filter the data by the current candidate
  candidate_data = new_df[new_df['Candidate'] == candidate]

  # Generate the classification report for the current candidate
  report = classification_report(candidate_data['Candidate'], candidate_data['Candidate GPT'], output_dict=True)

  # Store the report in the dictionary
  candidate_reports[candidate] = report

# Print the macro F1 score for each candidate
for candidate, report in candidate_reports.items():
  print(f"Macro F1 score for {candidate}: {report}")

Macro F1 score for Annalena Baerbock: {'Annalena Baerbock': {'precision': 1.0, 'recall': 0.8095238095238095, 'f1-score': 0.8947368421052632, 'support': 63}, 'Unknown': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'accuracy': 0.8095238095238095, 'macro avg': {'precision': 0.5, 'recall': 0.40476190476190477, 'f1-score': 0.4473684210526316, 'support': 63}, 'weighted avg': {'precision': 1.0, 'recall': 0.8095238095238095, 'f1-score': 0.8947368421052632, 'support': 63}}
Macro F1 score for Unknown: {'Annalena Baerbock': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'Armin Laschet': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'Christian Lindner': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'Markus Söder': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'Olaf Scholz': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'Unknown': {'precision': 1.0, 'recall': 0.890625, 'f1-score': 0.9421487603305785, 'support': 256}, 'accuracy': 0.890625, 'macro avg': {'precision': 0.16666666666666666, 'recall': 0.1484375, 'f1-score': 0.15702479338842976, 'support': 256}, 'weighted avg': {'precision': 1.0, 'recall': 0.890625, 'f1-score': 0.9421487603305785, 'support': 256}}
Macro F1 score for Armin Laschet: {'Armin Laschet': {'precision': 1.0, 'recall': 0.9777777777777777, 'f1-score': 0.9887640449438202, 'support': 180}, 'Unknown': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'accuracy': 0.9777777777777777, 'macro avg': {'precision': 0.5, 'recall': 0.4888888888888889, 'f1-score': 0.4943820224719101, 'support': 180}, 'weighted avg': {'precision': 1.0, 'recall': 0.9777777777777777, 'f1-score': 0.9887640449438202, 'support': 180}}
Macro F1 score for Christian Lindner: {'Christian Lindner': {'precision': 1.0, 'recall': 0.8709677419354839, 'f1-score': 0.9310344827586207, 'support': 62}, 'Unknown': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'accuracy': 0.8709677419354839, 'macro avg': {'precision': 0.5, 'recall': 0.43548387096774194, 'f1-score': 0.46551724137931033, 'support': 62}, 'weighted avg': {'precision': 1.0, 'recall': 0.8709677419354839, 'f1-score': 0.9310344827586207, 'support': 62}}
Macro F1 score for Markus Söder: {'Markus Söder': {'precision': 1.0, 'recall': 0.9247311827956989, 'f1-score': 0.9608938547486032, 'support': 93}, 'Unknown': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'accuracy': 0.9247311827956989, 'macro avg': {'precision': 0.5, 'recall': 0.46236559139784944, 'f1-score': 0.4804469273743016, 'support': 93}, 'weighted avg': {'precision': 1.0, 'recall': 0.9247311827956989, 'f1-score': 0.9608938547486032, 'support': 93}}
Macro F1 score for Olaf Scholz: {'Olaf Scholz': {'precision': 1.0, 'recall': 0.9135802469135802, 'f1-score': 0.9548387096774192, 'support': 81}, 'Unknown': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0}, 'accuracy': 0.9135802469135802, 'macro avg': {'precision': 0.5, 'recall': 0.4567901234567901, 'f1-score': 0.4774193548387096, 'support': 81}, 'weighted avg': {'precision': 1.0, 'recall': 0.9135802469135802, 'f1-score': 0.9548387096774192, 'support': 81}}

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))